# Generated by Django 2.2.6 on 2019-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='kitchen'),
        ),
        migrations.AddField(
            model_name='club',
            name='sports_broadcasts',
            field=models.BooleanField(default=False, verbose_name='sports broadcasts'),
        ),
        migrations.AddField(
            model_name='club',
            name='table_reservation',
            field=models.BooleanField(default=False, verbose_name='table reservation'),
        ),
    ]
