# Generated by Django 2.2.6 on 2020-01-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20191126_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='size',
            field=models.CharField(choices=[(12, '12 футов'), (11, '11 футов'), (10, '10 футов'), (9, '9 футов'), (8, '8 футов')], default=12, max_length=5, verbose_name='size'),
        ),
    ]
