# Generated by Django 2.2.6 on 2020-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20200108_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.CharField(blank=True, choices=[('12', '12 футов'), ('11', '11 футов'), ('10', '10 футов'), ('9', '9 футов'), ('8', '8 футов')], max_length=5, verbose_name='size'),
        ),
    ]
