# Generated by Django 2.2.6 on 2020-01-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_works_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='floor',
            field=models.CharField(blank=True, max_length=50, verbose_name='floor'),
        ),
    ]
