# Generated by Django 2.2.6 on 2020-02-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_club_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='description'),
        ),
    ]
