# Generated by Django 2.2.6 on 2020-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_table_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='description'),
        ),
    ]
