# Generated by Django 2.2.6 on 2020-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_price_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='school',
            field=models.BooleanField(default=False, verbose_name='school'),
        ),
    ]
