# Generated by Django 2.2.6 on 2021-09-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20210924_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date from'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date to'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='time from'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='time to'),
        ),
    ]
