# Generated by Django 2.2.6 on 2021-12-25 10:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_auto_20211217_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='type',
            field=models.CharField(choices=[('CM', 'Общий'), ('VP', 'VIP')], default='CM', max_length=5, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='table',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('RG', 'Обычный стол'), ('HT', 'Стол с подогревом'), ('DI', 'Стол с двойным освещением'), ('CN', 'Угловой стол')], default='RG', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='hall'),
        ),
    ]
