# Generated by Django 2.2.6 on 2021-12-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20211225_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_qr_code',
            field=models.BooleanField(default=False, verbose_name='entrance by QR code'),
        ),
        migrations.AlterField(
            model_name='club',
            name='is_medical_masks',
            field=models.BooleanField(default=False, verbose_name='entrance only with medical masks'),
        ),
    ]
