# Generated by Django 2.2.6 on 2022-01-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_auto_20220112_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='house',
            field=models.CharField(blank=True, max_length=50, verbose_name='находится в здании'),
        ),
    ]
