# Generated by Django 2.2.6 on 2022-01-14 05:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_club_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='billing',
            field=models.BooleanField(default=False, verbose_name='почасовая тарификация'),
        ),
        migrations.AddField(
            model_name='club',
            name='discount_cards',
            field=models.BooleanField(default=False, verbose_name='дисконтные карты'),
        ),
        migrations.AddField(
            model_name='table',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='customer_categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('AL', 'Всем'), ('RT', 'Пенсионерам'), ('PP', 'Школьникам'), ('ST', 'Студентам'), ('BD', 'Именинникам'), ('RC', 'Постоянным клиентам'), ('SB', 'Подписчикам')], default='AL', max_length=20, verbose_name='customer categories'),
        ),
    ]
